import * as fs from "fs";
import * as path from "path";
import type { MetaStatePayload } from "../ws_protocol";
import { materializeAiGridConfigs } from "./track_ai_setup";
import { rivalModifiersForTeam } from "./ai_rival_season";
import { regulationForRound } from "./regulations";
import {
  generateGrid,
  generatePlayerOnlyGrid,
  writeEntriesFile,
  type GeneratedEntry,
} from "./grid_generator";
import type { StartPrivateTestPayload } from "../ws_protocol";
import {
  privateTestWeatherSeed,
  trackMonthForPrivateTest,
} from "./private_test";
import { writeAllFleetConfigs } from "./car_builder";
import { loadCarPlatforms } from "./car_marketplace";
import { validateFleetRegulations } from "./fleet";
import { writeCarConditionsFile } from "./car_condition";
import { exportRuntimeDrivers, resolveCarDriverRoster, buildSessionEntryRosters, rostersForCompetingEntries, type SessionEntryRosters } from "./driver_catalog";
import {
  formatToDurationSeconds,
  trackDisplayName,
  trackJsonPath,
  WEC_2026_CALENDAR,
} from "./track_catalog";
import { formatWeatherConfigLines, monthName, resolveTrackWeather } from "./track_climate";
import {
  applyQualifyingGrid,
  sessionDurationSeconds,
  sessionDisplayLabel,
  type QualifyingResult,
  type WeekendSessionType,
} from "./weekend_sessions";

export interface BuiltRace {
  raceConfigPath: string;
  entriesPath: string;
  staffConfigPath: string;
  driverConfigPath: string;
  trackName: string;
  trackConfigPath: string;
  targetLaps: number;
  targetDurationSeconds: number;
  raceFormat: string;
  roundNumber: number;
  entries: GeneratedEntry[];
  playerEntryId: string;
  managedEntryIds: string[];
  /** Driver rosters for entries that actually started this session. */
  sessionEntryRosters: SessionEntryRosters;
  weatherContext: {
    trackId: string;
    month: number;
    monthName: string;
    biome: string;
    label: string;
    rainWeight: number;
  };
  sessionType: WeekendSessionType;
  sessionLabel: string;
}

export interface BuildRaceOptions {
  sessionType?: WeekendSessionType;
  qualiResults?: QualifyingResult[];
}

export interface BuildPrivateTestOptions {
  payload: StartPrivateTestPayload;
}

function writeStaffConfig(
  repoRoot: string,
  relPath: string,
  meta: MetaStatePayload,
  entries: GeneratedEntry[],
): string {
  const abs = path.join(repoRoot, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  const carToEntry = new Map(
    entries
      .filter((e) => e.fleetCarId && e.teamName === meta.teamName)
      .map((e) => [e.fleetCarId!, e.entryId]),
  );
  const lines = [
    "# Runtime staff — pit modifiers for sim (generated by server)",
  ];
  for (const s of meta.staff ?? []) {
    if (s.assignedCarId) {
      const entryId = carToEntry.get(s.assignedCarId);
      if (entryId) {
        lines.push(`staff=${entryId},${s.role},${s.name},${s.skill}`);
        continue;
      }
    }
    lines.push(`staff=${s.role},${s.name},${s.skill}`);
  }
  fs.writeFileSync(abs, lines.join("\n") + "\n");
  return relPath;
}

export function buildRaceForRound(
  repoRoot: string,
  meta: MetaStatePayload,
  options: BuildRaceOptions = {},
): BuiltRace | null {
  const round = meta.calendar.find((e) => e.round === meta.currentRound);
  if (!round) return null;

  const fleetErr = validateFleetRegulations(meta.fleet ?? []);
  if (fleetErr) return null;

  const sessionType = options.sessionType ?? "race";
  const sessionLabel = sessionDisplayLabel(sessionType);
  const durationSec = sessionDurationSeconds(
    sessionType,
    round.format,
    formatToDurationSeconds,
  );

  const platformMap = new Map(
    loadCarPlatforms(repoRoot).map((p) => [p.id, p.templatePath]),
  );
  writeAllFleetConfigs(repoRoot, meta, platformMap, round.trackId);

  const trackConfigPath = trackJsonPath(round.trackId);
  const regulation = regulationForRound(round.round);

  const playerCarId =
    meta.playerCarId ?? meta.activeCarId ?? meta.fleet?.[0]?.id;

  let entries = generateGrid({
    repoRoot,
    playerTeamName: meta.teamName,
    playerEntryId: meta.playerEntryId,
    playerFleet: meta.fleet,
    playerCarId,
    playerClassId: meta.playerClassId ?? "Hypercar",
    seasonYear: meta.seasonYear,
    includeReserves: round.trackId === "lemans_la_sarthe",
  });

  if (sessionType === "race" && options.qualiResults?.length) {
    entries = applyQualifyingGrid(entries, options.qualiResults);
  }

  const managedEntryIds = entries
    .filter((e) => e.teamName === meta.teamName && e.fleetCarId)
    .map((e) => e.entryId);

  for (const entry of entries) {
    if (entry.isPlayer) continue;
    const rel = `configs/runtime/ai/grid_${entry.grid}_${path.basename(entry.carConfigPath)}`;
    const src = path.join(repoRoot, entry.carConfigPath);
    const dest = path.join(repoRoot, rel);
    if (!fs.existsSync(src)) continue;
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    entry.carConfigPath = rel;
  }
  materializeAiGridConfigs(
    repoRoot,
    entries,
    round.trackId,
    (teamName) => rivalModifiersForTeam(teamName, meta.aiRivalSeason),
  );

  const playerFleetEntry = entries.find((e) => e.fleetCarId === playerCarId);
  const resolvedPlayerEntryId =
    playerFleetEntry?.entryId ??
    managedEntryIds[0] ??
    entries.find((e) => e.isPlayer)?.entryId ??
    meta.playerEntryId;

  const entriesPath = writeEntriesFile(
    repoRoot,
    "configs/runtime/entries.txt",
    entries,
  );
  const staffConfigPath = writeStaffConfig(
    repoRoot,
    "configs/runtime/staff.txt",
    meta,
    entries,
  );

  const playerFleetCarIds = new Set(
    entries
      .filter((e) => e.fleetCarId && e.teamName === meta.teamName)
      .map((e) => e.fleetCarId!),
  );
  const fleetById = new Map((meta.fleet ?? []).map((c) => [c.id, c]));
  const teamRoster = meta.driverRoster ?? [];
  const playerDriverEntries = [...playerFleetCarIds]
    .map((carId) => {
      const car = fleetById.get(carId);
      if (!car) return null;
      const roster = resolveCarDriverRoster(
        teamRoster,
        car.assignedDriverIds,
      );
      if (!roster.length) return null;
      return {
        teamName: meta.teamName,
        carNumber: car.carNumber,
        roster,
      };
    })
    .filter((e): e is NonNullable<typeof e> => e !== null);

  const driverExportOptions = {
    playerTeamName: meta.teamName,
    playerRoster: teamRoster,
    playerEntries: playerDriverEntries,
    rosterOverrides: meta.aiRivalSeason?.rosterOverrides,
  };
  const allSessionRosters = buildSessionEntryRosters(repoRoot, driverExportOptions);
  const driverConfigPath = exportRuntimeDrivers(
    repoRoot,
    driverExportOptions,
    allSessionRosters,
  );
  const sessionEntryRosters = rostersForCompetingEntries(entries, allSessionRosters);

  const calendarEvent =
    WEC_2026_CALENDAR.find((e) => e.round === round.round) ?? null;
  const raceMonth = round.month ?? calendarEvent?.month ?? 6;
  const rngSeed = meta.seasonYear * 1000 + round.round;
  const resolvedWeather = resolveTrackWeather(round.trackId, raceMonth, rngSeed);

  const raceConfigPath = "configs/runtime/race.txt";
  const absRace = path.join(repoRoot, raceConfigPath);
  fs.mkdirSync(path.dirname(absRace), { recursive: true });

  const lines = [
    `# Runtime race — ${sessionLabel} (generated by server from calendar)`,
    "part_catalog=configs/part_catalog.txt",
    "physics_config=configs/physics_config.txt",
    `track_config=${trackConfigPath}`,
    "car_config=configs/car_config.txt",
    durationSec > 0 ? "target_laps=0" : "target_laps=3",
    durationSec > 0 ? `target_duration_hours=${durationSec / 3600}` : "",
    "sim_timestep=0.1",
    "telemetry_output=",
    `entries=${entriesPath}`,
    `class_rules=${regulation.classRulesPath}`,
    `staff_config=${staffConfigPath}`,
    `driver_config=${driverConfigPath}`,
    `session_mode=${sessionType}`,
    ...formatWeatherConfigLines(resolvedWeather, rngSeed),
  ].filter(Boolean);

  const carConditionsPath = "configs/runtime/car_conditions.txt";
  const absConditions = path.join(repoRoot, carConditionsPath);
  writeCarConditionsFile(
    absConditions,
    entries
      .filter((e) => e.fleetCarId && e.teamName === meta.teamName)
      .map((e) => ({
        entryId: e.entryId,
        condition: (meta.fleet ?? []).find((c) => c.id === e.fleetCarId)
          ?.carCondition,
      })),
  );
  lines.push(`car_conditions=${carConditionsPath}`);

  fs.writeFileSync(absRace, lines.join("\n") + "\n");

  return {
    raceConfigPath,
    entriesPath,
    staffConfigPath,
    driverConfigPath,
    trackName: round.eventName ?? trackDisplayName(round.trackId),
    trackConfigPath,
    targetLaps: durationSec > 0 ? 0 : 3,
    targetDurationSeconds: durationSec,
    raceFormat: round.format,
    roundNumber: round.round,
    entries,
    playerEntryId: resolvedPlayerEntryId,
    managedEntryIds,
    sessionEntryRosters,
    weatherContext: {
      trackId: round.trackId,
      month: raceMonth,
      monthName: monthName(raceMonth),
      biome: resolvedWeather.biome,
      label: resolvedWeather.label,
      rainWeight: resolvedWeather.rainWeight,
    },
    sessionType,
    sessionLabel,
  };
}

export function buildPrivateTestSession(
  repoRoot: string,
  meta: MetaStatePayload,
  options: BuildPrivateTestOptions,
): BuiltRace | null {
  const { payload } = options;
  const trackId = payload.trackId;
  const selectedFleet = (meta.fleet ?? []).filter((c) =>
    payload.carIds.includes(c.id),
  );
  if (!selectedFleet.length) return null;

  const sessionType: WeekendSessionType = "practice";
  const sessionLabel = sessionDisplayLabel(sessionType);
  const durationSec = payload.durationHours * 3600;

  const platformMap = new Map(
    loadCarPlatforms(repoRoot).map((p) => [p.id, p.templatePath]),
  );
  writeAllFleetConfigs(repoRoot, meta, platformMap, trackId);

  const trackConfigPath = trackJsonPath(trackId);
  const round = meta.calendar.find((e) => e.round === meta.currentRound);
  const regulation = regulationForRound(round?.round ?? meta.currentRound);

  const playerCarId =
    meta.playerCarId ?? meta.activeCarId ?? selectedFleet[0]?.id;

  const entries = generatePlayerOnlyGrid({
    playerTeamName: meta.teamName,
    playerFleet: selectedFleet,
    playerCarId,
  });

  const managedEntryIds = entries.map((e) => e.entryId);

  const playerFleetEntry = entries.find((e) => e.fleetCarId === playerCarId);
  const resolvedPlayerEntryId =
    playerFleetEntry?.entryId ??
    managedEntryIds[0] ??
    entries[0]?.entryId ??
    meta.playerEntryId;

  const runtimePrefix = "configs/runtime/private_test";
  const entriesPath = writeEntriesFile(
    repoRoot,
    `${runtimePrefix}/entries.txt`,
    entries,
  );
  const staffConfigPath = writeStaffConfig(
    repoRoot,
    `${runtimePrefix}/staff.txt`,
    meta,
    entries,
  );

  const fleetById = new Map(selectedFleet.map((c) => [c.id, c]));
  const teamRoster = meta.driverRoster ?? [];
  const playerDriverEntries = payload.carIds
    .map((carId) => {
      const car = fleetById.get(carId);
      if (!car) return null;
      const roster = resolveCarDriverRoster(
        teamRoster,
        payload.driverAssignments[carId],
      );
      if (!roster.length) return null;
      return {
        teamName: meta.teamName,
        carNumber: car.carNumber,
        roster,
      };
    })
    .filter((e): e is NonNullable<typeof e> => e !== null);

  const driverExportOptions = {
    playerTeamName: meta.teamName,
    playerRoster: teamRoster,
    playerEntries: playerDriverEntries,
    rosterOverrides: meta.aiRivalSeason?.rosterOverrides,
  };
  const allSessionRosters = buildSessionEntryRosters(repoRoot, driverExportOptions);
  const driverConfigPath = exportRuntimeDrivers(
    repoRoot,
    driverExportOptions,
    allSessionRosters,
    `${runtimePrefix}/drivers.txt`,
  );
  const sessionEntryRosters = rostersForCompetingEntries(entries, allSessionRosters);

  const raceMonth = trackMonthForPrivateTest(trackId);
  const rngSeed = privateTestWeatherSeed(meta.seasonYear, trackId);
  const resolvedWeather = resolveTrackWeather(trackId, raceMonth, rngSeed);

  const raceConfigPath = `${runtimePrefix}/race.txt`;
  const absRace = path.join(repoRoot, raceConfigPath);
  fs.mkdirSync(path.dirname(absRace), { recursive: true });

  const lines = [
    `# Runtime private test — ${sessionLabel} (generated by server)`,
    "part_catalog=configs/part_catalog.txt",
    "physics_config=configs/physics_config.txt",
    `track_config=${trackConfigPath}`,
    "car_config=configs/car_config.txt",
    "target_laps=0",
    `target_duration_hours=${durationSec / 3600}`,
    "sim_timestep=0.1",
    "telemetry_output=",
    `entries=${entriesPath}`,
    `class_rules=${regulation.classRulesPath}`,
    `staff_config=${staffConfigPath}`,
    `driver_config=${driverConfigPath}`,
    `session_mode=${sessionType}`,
    ...formatWeatherConfigLines(resolvedWeather, rngSeed),
  ];

  const carConditionsPath = `${runtimePrefix}/car_conditions.txt`;
  const absConditions = path.join(repoRoot, carConditionsPath);
  writeCarConditionsFile(
    absConditions,
    entries
      .filter((e) => e.fleetCarId)
      .map((e) => ({
        entryId: e.entryId,
        condition: selectedFleet.find((c) => c.id === e.fleetCarId)?.carCondition,
      })),
  );
  lines.push(`car_conditions=${carConditionsPath}`);

  fs.writeFileSync(absRace, lines.join("\n") + "\n");

  return {
    raceConfigPath,
    entriesPath,
    staffConfigPath,
    driverConfigPath,
    trackName: `Private Test — ${trackDisplayName(trackId)}`,
    trackConfigPath,
    targetLaps: 0,
    targetDurationSeconds: durationSec,
    raceFormat: "private_test",
    roundNumber: -1,
    entries,
    playerEntryId: resolvedPlayerEntryId,
    managedEntryIds,
    sessionEntryRosters,
    weatherContext: {
      trackId,
      month: raceMonth,
      monthName: monthName(raceMonth),
      biome: resolvedWeather.biome,
      label: resolvedWeather.label,
      rainWeight: resolvedWeather.rainWeight,
    },
    sessionType,
    sessionLabel,
  };
}
