import * as fs from "fs";
import * as path from "path";
import type { MetaStatePayload } from "../ws_protocol";
import { regulationForRound } from "./regulations";
import { generateGrid, writeEntriesFile, type GeneratedEntry } from "./grid_generator";
import { writeAllFleetConfigs } from "./car_builder";
import { loadCarPlatforms } from "./car_marketplace";
import { validateFleetRegulations } from "./fleet";
import { exportRuntimeDrivers, resolveCarDriverRoster } from "./driver_catalog";
import {
  formatToDurationSeconds,
  trackDisplayName,
  trackJsonPath,
} from "./track_catalog";

export interface BuiltRace {
  raceConfigPath: string;
  entriesPath: string;
  staffConfigPath: string;
  driverConfigPath: string;
  trackName: string;
  trackConfigPath: string;
  targetLaps: number;
  targetDurationSeconds: number;
  raceFormat: string;
  roundNumber: number;
  entries: GeneratedEntry[];
  playerEntryId: string;
  managedEntryIds: string[];
}

function writeStaffConfig(
  repoRoot: string,
  relPath: string,
  meta: MetaStatePayload,
): string {
  const abs = path.join(repoRoot, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  const lines = [
    "# Runtime staff — pit modifiers for sim (generated by server)",
    ...meta.staff.map((s) => `staff=${s.role},${s.name},${s.skill}`),
  ];
  fs.writeFileSync(abs, lines.join("\n") + "\n");
  return relPath;
}

export function buildRaceForRound(
  repoRoot: string,
  meta: MetaStatePayload,
): BuiltRace | null {
  const round = meta.calendar.find((e) => e.round === meta.currentRound);
  if (!round) return null;

  const fleetErr = validateFleetRegulations(meta.fleet ?? []);
  if (fleetErr) return null;

  const platformMap = new Map(
    loadCarPlatforms(repoRoot).map((p) => [p.id, p.templatePath]),
  );
  writeAllFleetConfigs(repoRoot, meta, platformMap);

  const trackConfigPath = trackJsonPath(round.trackId);
  const durationSec = formatToDurationSeconds(round.format);
  const regulation = regulationForRound(round.round);

  const playerCarId =
    meta.playerCarId ?? meta.activeCarId ?? meta.fleet?.[0]?.id;

  const entries = generateGrid({
    repoRoot,
    playerTeamName: meta.teamName,
    playerEntryId: meta.playerEntryId,
    playerFleet: meta.fleet,
    playerCarId,
    playerClassId: meta.playerClassId ?? "Hypercar",
    seasonYear: meta.seasonYear,
    includeReserves: round.trackId === "lemans_la_sarthe",
  });

  const managedEntryIds = entries
    .filter((e) => e.teamName === meta.teamName && e.fleetCarId)
    .map((e) => e.entryId);

  const playerFleetEntry = entries.find((e) => e.fleetCarId === playerCarId);
  const resolvedPlayerEntryId =
    playerFleetEntry?.entryId ??
    managedEntryIds[0] ??
    entries.find((e) => e.isPlayer)?.entryId ??
    meta.playerEntryId;

  const entriesPath = writeEntriesFile(
    repoRoot,
    "configs/runtime/entries.txt",
    entries,
  );
  const staffConfigPath = writeStaffConfig(
    repoRoot,
    "configs/runtime/staff.txt",
    meta,
  );

  const playerFleetCarIds = new Set(
    entries
      .filter((e) => e.fleetCarId && e.teamName === meta.teamName)
      .map((e) => e.fleetCarId!),
  );
  const fleetById = new Map((meta.fleet ?? []).map((c) => [c.id, c]));
  const teamRoster = meta.driverRoster ?? [];
  const playerDriverEntries = [...playerFleetCarIds]
    .map((carId) => {
      const car = fleetById.get(carId);
      if (!car) return null;
      const roster = resolveCarDriverRoster(
        teamRoster,
        car.assignedDriverIndices,
      );
      if (!roster.length) return null;
      return {
        teamName: meta.teamName,
        carNumber: car.carNumber,
        roster,
      };
    })
    .filter((e): e is NonNullable<typeof e> => e !== null);

  const driverConfigPath = exportRuntimeDrivers(repoRoot, {
    playerEntries: playerDriverEntries,
  });

  const raceConfigPath = "configs/runtime/race.txt";
  const absRace = path.join(repoRoot, raceConfigPath);
  fs.mkdirSync(path.dirname(absRace), { recursive: true });

  const lines = [
    "# Runtime race — generated by server from calendar",
    "part_catalog=configs/part_catalog.txt",
    "physics_config=configs/physics_config.txt",
    `track_config=${trackConfigPath}`,
    "car_config=configs/car_config.txt",
    durationSec > 0 ? "target_laps=0" : "target_laps=3",
    durationSec > 0 ? `target_duration_hours=${durationSec / 3600}` : "",
    "sim_timestep=0.1",
    "telemetry_output=",
    `entries=${entriesPath}`,
    `class_rules=${regulation.classRulesPath}`,
    `staff_config=${staffConfigPath}`,
    `driver_config=${driverConfigPath}`,
  ].filter(Boolean);

  fs.writeFileSync(absRace, lines.join("\n") + "\n");

  return {
    raceConfigPath,
    entriesPath,
    staffConfigPath,
    driverConfigPath,
    trackName: round.eventName ?? trackDisplayName(round.trackId),
    trackConfigPath,
    targetLaps: durationSec > 0 ? 0 : 3,
    targetDurationSeconds: durationSec,
    raceFormat: round.format,
    roundNumber: round.round,
    entries,
    playerEntryId: resolvedPlayerEntryId,
    managedEntryIds,
  };
}
